const initialFriends = [
  {
    id: 118836,
    firstName: "Clark",
    lastName: "Kent",
    email: "clark@justiceLeague.com",
    image:
      "https://i2.wp.com/images4.fanpop.com/image/photos/18000000/smallville-tom-welling-18071939-1186-1500.jpg",
    balance: -7,
  },
  {
    id: 933372,
    firstName: "Lios",
    lastName: "Lane",
    email: "lios@justiceLeague.com",
    image: "https://upload.wikimedia.org/wikipedia/en/9/9d/Loissmall.jpg",
    balance: 20,
  },
  {
    id: 499476,
    firstName: "Lex",
    lastName: "Lurther",
    email: "lex@justiceLeague.com",
    image:
      "https://superlessons.wordpress.com/wp-content/uploads/2016/01/lex-luthor.jpg",
    balance: 0,
  },
  {
    id: 499477,
    firstName: "Bruce",
    lastName: "Wayne",
    email: "bruce@justiceLeague.com",
    image: "https://i.redd.it/1vy90yxx5jh71.jpg",
    balance: 0,
  },
  {
    id: 499479,
    firstName: "Chloe",
    lastName: "Sullivan",
    email: "chloe@justiceLeague.com",
    image: "https://upload.wikimedia.org/wikipedia/en/6/6d/Fallisonmackf.jpg",
    balance: 0,
  },
  {
    id: 499471,
    firstName: "Oliver",
    lastName: "Queen",
    email: "oliver@justiceLeague.com",
    image: "https://i.pravatar.cc/48?u=499476",
    balance: 0,
  },
  {
    id: 4994,
    firstName: "Felicity",
    lastName: "Smoake",
    email: "facility@justiceLeague.com",
    image: "https://i.pravatar.cc/48?u=499476",
    balance: 0,
  },
  {
    id: 49941,
    firstName: "Roy",
    lastName: "Harper",
    email: "roy@justiceLeague.com",
    image: "https://i.pravatar.cc/48?u=499476",
    balance: 0,
  },
  {
    id: 49471,
    firstName: "Kara",
    lastName: "Zor-el",
    email: "kara@justiceLeague.com",
    image: "https://i.pravatar.cc/48?u=499476",
    balance: 0,
  },
  {
    id: 4471,
    firstName: "Arthur",
    lastName: "Curry",
    email: "arthur@justiceLeague.com",
    image: "https://i.pravatar.cc/48?u=499476",
    balance: 0,
  },
];

export default initialFriends;
